CREATE TABLE CIDADE(
  CIDID INT IDENTITY (1,1) PRIMARY KEY,
  CIDDESCRICAO VARCHAR(100) NOT NULL,
  ESTID INT NOT NULL REFERENCES ESTADO(ESTID)
)
GO
SELECT * FROM ESTADO
SELECT * FROM CIDADE
INSERT CIDADE VALUES ('ESTANCIA',1)


CREATE TABLE TIPODOCUMENTO(
TIPID INT IDENTITY (1,1) PRIMARY KEY,
TIPDESCRICAO VARCHAR(100) NOT NULL UNIQUE
)


CREATE TABLE PESSOA(
PESID INT IDENTITY (1,1) PRIMARY KEY,
PESNOME VARCHAR (100) NOT NULL,
PESCPF VARCHAR (20) NOT NULL,
PESCNPJ VARCHAR (20) NOT NULL,
PESSEXO BIT NOT NULL,
PESENDERECO VARCHAR (100) NOT NULL,
CIDID INT 
)

ALTER TABLE PESSOA
ADD PESTELEFONE VARCHAR(30);

INSERT PESSOA (PESNOME,PESCPF,PESCNPJ,PESSEXO)
VALUES ('REGI','05156',  NULL,'INDECISO')

ALTER TABLE PESSOA
ADD PESSCEP VARCHAR(30)  NULL;

DELETE, SELECT, UPDATE

CREATE TABLE TIPOPESSOA (
TIPID INT IDENTITY (1,1) PRIMARY KEY,
TIPDescricao VARCHAR(100) NOT NULL,
)

CREATE TABLE PROCESSO (
PROID INT IDENTITY (1,1) PRIMARY KEY,
PRORELATO VARCHAR (1000) NOT NULL,
PRODATA DATETIME NOT NULL,
)

CREATE TABLE PESSOAPROCESSO(
PESID INT NOT NULL,
PROID INT NOT NULL,
TIPID INT NOT NULL,
DATAVINCULO DATETIME
CONSTRAINT PK_PESSOAPROCESSO PRIMARY KEY(PESID,PROID),

CONSTRAINT FK_PESSOAPROCESSO_PESSOA FOREIGN KEY (PESID)
  REFERENCES PESSOA(PESID),
CONSTRAINT FK_PESSOAPROCESSO_PROID FOREIGN KEY (PROID)
  REFERENCES PROCESSO(PROID),
CONSTRAINT FK_PESSOAPROCESSO_TIPO FOREIGN KEY (TIPID)
  REFERENCES TIPOPESSOA(TIPID),