USE MASTER
GO
CREATE DATABASE ListasDB
GO
USE ListasDB
CREATE TABLE Responsavel (
RespID INT IDENTITY (1,1) PRIMARY KEY,
RespNome VARCHAR(100) NOT NULL,
RespIdade INT NOT NULL,
)
GO 
SELECT * FROM Responsavel
INSERT Responsavel VALUES ('Maria','18')
GO
CREATE TABLE Aluno (
AlunoID INT IDENTITY (1,1) PRIMARY KEY,
AlunoNome VARCHAR (100) NOT NULL,
AlunoSobrenome VARCHAR (100) NOT NULL,
)
GO 
SELECT * FROM Aluno
INSERT Aluno VALUES ('Joao','Silva')
GO
CREATE TABLE Curso (
CursoID INT IDENTITY (1,1) PRIMARY KEY,
CursoDescricao VARCHAR (100) NOT NULL,
CursoArea VARCHAR (250) NOT NULL,
)
GO
SELECT * FROM Curso
INSERT Curso VALUES ('fazer sistema','tds')
GO
CREATE TABLE Sala (
SalaID INT IDENTITY (1,1) PRIMARY KEY,
SalaDescricao VARCHAR (100) NOT NULL,
)
GO
SELECT * FROM Sala
INSERT Sala VALUES ('tecnologia')
GO
CREATE TABLE Categoria (
CatID INT IDENTITY (1,1) PRIMARY KEY,
CatDescricao VARCHAR (100) NOT NULL,
)
GO
SELECT * FROM Categoria
INSERT Categoria VALUES ('ti')
GO
CREATE TABLE Recurso (
RecID INT IDENTITY (1,1) PRIMARY KEY,
RecDescricao VARCHAR (100) NOT NULL,
RecQtd INT NOT NULL,
CatID INT FOREIGN KEY REFERENCES Categoria,
)
GO
SELECT * FROM Recurso
INSERT Recurso VALUES ('compt','3','1')
GO
CREATE TABLE Departamento (
DepID INT IDENTITY (1,1) PRIMARY KEY,
DepNome VARCHAR (100) NOT NULL,
)
GO
SELECT * FROM Departamento
INSERT Departamento VALUES ('tid')
GO
CREATE TABLE Serie (
SerieID INT IDENTITY (1,1) PRIMARY KEY,
SerieNome VARCHAR (100) NOT NULL,
)
GO
SELECT * FROM Serie
INSERT Serie VALUES ('segundo ano')
GO
CREATE TABLE NivelDeEnsino (
NivelDeEnsinoID INT IDENTITY (1,1) PRIMARY KEY,
NivelDeEnsinoDescricao VARCHAR (100) NOT NULL,
)
GO
SELECT * FROM NivelDeEnsino
INSERT NivelDeEnsino VALUES ('intermediario')
GO
CREATE TABLE FUNCIONARIO (
FuncID INT IDENTITY (1,1) PRIMARY KEY,
FuncNome VARCHAR (100) NOT NULL,
FuncData DATETIME NOT NULL,
DepID INT FOREIGN KEY REFERENCES Departamento,
)
GO
SELECT * FROM FUNCIONARIO
INSERT FUNCIONARIO VALUES ('Alice','2023-01-02','2')
