USE MASTER
GO
CREATE DATABASE BDGURI
GO
USE BDGURI
CREATE TABLE TBLOGIN (
  LOGID INT IDENTITY (1,1) PRIMARY KEY,
  LOGNOME VARCHAR (50) NOT NULL,
  LOGSENHA VARCHAR(100) NOT NULL,

  )
  INSERT TBLOGIN (LOGNOME,LOGSENHA) VALUES ('icaro', '123')

  SELECT * FROM TBLOGIN
